name: developer_cambodia
description: Developer-Cambodia-E-learning

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/logos/
     - assets/logos/google.png
     - assets/images/



  fonts:
    - family: NotoSerifKhmer
      fonts:
        - asset: assets/fonts/Black900.ttf
          weight: 900
        - asset: assets/fonts/Bold700.ttf
          weight: 700
        - asset: assets/fonts/ExtraBold800.ttf
          weight: 800
        - asset: assets/fonts/ExtraLight200.ttf
          weight: 200
        - asset: assets/fonts/Light300.ttf
          weight: 300
        - asset: assets/fonts/Medium500.ttf
          weight: 500
        - asset: assets/fonts/Regular400.ttf
          weight: 400
        - asset: assets/fonts/SemiBold600.ttf
          weight: 600
        - asset: assets/fonts/Thin100.ttf
          weight: 100

